version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: broker-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: broker_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - broker-net

  broker-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: broker-api-app
    container_name: broker-api
    depends_on:
      - mysql
    ports:
      - "9090:9090"
    networks:
      - broker-net
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - broker-api

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/dashboards/files:/etc/grafana/provisioning/dashboards/files
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
volumes:
  mysql-data:
  grafana-data:

networks:
  broker-net:
